# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "404b1dcd8562143be56b2dd81dec2270"
name = "See It"
application_url = "https://see-it-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [ 
  "https://see-it-production.up.railway.app/auth/callback",
  "https://see-it-production.up.railway.app/api/auth"
]

[app_proxy]
url = "https://see-it-production.up.railway.app/app-proxy"
subpath = "see-it"
prefix = "apps"
