api_version = "2024-01"

[[extensions]]
name = "See It Extension"
handle = "see-it-extension"

uid = "0cb5731f-97cf-62e9-7179-d1695b626b8d7c7a5f45"

type = "theme"

[settings]
  [[settings.fields]]
  key = "button_label"
  type = "text"
  name = "Button Label"
  default = "See it in your room"
